name: Waifu Generator CI

on:
  push:
    branches:
      - main
  schedule:
  - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '>=12.14.1'
    - name: Install dependecies
      run: npm install
    - name: Scrape data waifu
      run: npm run start:scrape
    - name: Commit files
      run: |
        git config --local user.email "satyawikananda456@gmail.com"
        git config --local user.name "satyawikananda"
        git add .
        git commit -m "chore: Update data waifu" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
